-
   name: 'Print list of fruits'
   hosts: all
   vars:
     fruits:
       - Apple
       - Banana
       - Grapes
       - Orange
   tasks:
     -
       command: 'echo "{{ item }}"'
       with_items: '{{ fruits }}'
