-
  name: Copy file to target servers
  hosts: all
  tasks:
    - name: Copy file
      copy:
        src: /home/osboxes/ansible-demos-exercises/ansible/exercise-1-copy-file/test-file.txt
        dest: /tmp
